title: "Ahmed Elmeligy's Blog"
tagline: "Blog migrated from WordPress using Chirpy"
url: "https://ameligy.github.io"
baseurl: ""
theme: jekyll-theme-chirpy
lang: en
timezone: Canada/Mountain
author:
  name: Ahmed Elmeligy
  email: 
