title: "Ahmed Elmeligy"
author: "Ahmed Elmeligy"
email: "your@email.com"
description: >- 
  Blog migrated from WordPress using Beautiful Jekyll.
baseurl: "" 
url: "https://ameligy.github.io"
theme: jekyll-theme-cayman

# Social
twitter_username: ahmedelmeligy
github_username:  ameligy

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
